[package]
name = "gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "gateway"
path = "src/lib.rs"

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
actix-web.workspace = true
actix-ws.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
zenoh.workspace = true
log.workspace = true
env_logger.workspace = true
thiserror.workspace = true
futures-util.workspace = true
cdr = "0.2.4"

[dev-dependencies]
actix-web = { workspace = true }
tokio-tungstenite = "0.24"

[[test]]
name = "domain_contract_test"
path = "tests/domain_contract_test.rs"

[[test]]
name = "ws_gateway_test"
path = "tests/ws_gateway_test.rs"

[[test]]
name = "throttler_action_test"
path = "tests/throttler_action_test.rs"
