// Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
use serde::{Deserialize, Deserializer, Serialize};
use thiserror::Error;

/// Error types encountered in domain validation and key resolution.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DomainError {
    #[error("Invalid robot ID: must be non-empty and not contain slashes")]
    InvalidRobotId,
    #[error("Invalid joint positions: must contain finite float values")]
    InvalidJointPositions,
}

/// Actuation action to execute on dexterous palm
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PalmAction {
    Grasp,
    Release,
}

/// Pre-defined canonical UR5e posture
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PoseName {
    Home,
    Ready,
    InspectPose,
}

/// Type of object to spawn
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SpawnObjectType {
    Gear,
}

/// Gear color class routing to its spindle tower
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum GearColor {
    White,
    Green,
    Blue,
}

impl Default for GearColor {
    fn default() -> Self {
        Self::White
    }
}

/// Operational command type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommandType {
    Ping,
    TeleopJointTarget,
    PalmActuate,
    TrajectoryExecute,
    EmergencyStop,
    ResetFault,
    Engage,
    Standby,
    SpawnObject,
    ClearWorkspace,
    PickAndPlaceTarget,
}

/// Current lifecycle state of the robotic manipulator
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RobotState {
    Booting,
    Standby,
    Idle,
    Executing,
    Fault,
}

/// Canonical UR5e 6-DoF joint names in kinematic sequence
pub const UR5E_JOINTS: [&str; 6] = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
];

/// Alias for canonical joint names.
pub const CANONICAL_UR5E_JOINTS: [&str; 6] = UR5E_JOINTS;

/// Canonical default robot identifier across all services
pub const DEFAULT_ROBOT_ID: &str = "arm-ur5";

/// White spindle tower base coordinates in meters (REP-103 robot base frame)
pub const WHITE_TOWER: [f64; 3] = [0.4, -0.3, 0.0];

/// Green spindle tower base coordinates in meters (REP-103 robot base frame)
pub const GREEN_TOWER: [f64; 3] = [0.55, -0.3, 0.0];

/// Blue spindle tower base coordinates in meters (REP-103 robot base frame)
pub const BLUE_TOWER: [f64; 3] = [0.7, -0.3, 0.0];

/// Scrap bin coordinates in meters (REP-103 robot base frame)
pub const SCRAP_BIN: [f64; 3] = [0.4, 0.28, 0.0];

/// Maximum gears per spindle tower
pub const TOWER_CAPACITY: i64 = 10;

/// Vertical stacking step per gear in meters
pub const STACK_STEP_M: f64 = 0.02;

/// Array of exactly 6 joint positions in radians.
pub type ArmJointPositions = [f64; 6];

fn deserialize_finite_joints<'de, D>(deserializer: D) -> Result<ArmJointPositions, D::Error>
where
    D: Deserializer<'de>,
{
    let arr = <ArmJointPositions>::deserialize(deserializer)?;
    for (idx, &val) in arr.iter().enumerate() {
        if !val.is_finite() {
            return Err(serde::de::Error::custom(format!(
                "Joint position at index {idx} must be a finite number"
            )));
        }
    }
    Ok(arr)
}

/// Validates that an array of joint positions contains only finite floats.
///
/// # Errors
/// Returns [`DomainError::InvalidJointPositions`] if any joint position is non-finite (NaN or Inf).
pub fn validate_joint_positions(joint_positions: &ArmJointPositions) -> Result<(), DomainError> {
    if !joint_positions.iter().all(|&p| p.is_finite()) {
        return Err(DomainError::InvalidJointPositions);
    }
    Ok(())
}

/// Typed payload for PALM_ACTUATE command to toggle suction or grasp status
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PalmActuatePayload {
    pub action: PalmAction,
}

/// Typed payload for TRAJECTORY_EXECUTE command dispatching canned or custom trajectories
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct TrajectoryExecutePayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pose_name: Option<PoseName>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub waypoints: Option<Vec<ArmJointPositions>>,
}

/// Typed payload for EMERGENCY_STOP command
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct EmergencyStopPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// Typed payload for RESET_FAULT command
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct ResetFaultPayload {
}

/// Typed payload for ENGAGE command activating EdgeNode from STANDBY
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EngagePayload {
}

/// Typed payload for STANDBY command parking EdgeNode to idle
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StandbyPayload {
}

/// Typed payload for SPAWN_OBJECT command
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SpawnObjectPayload {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub object_type: SpawnObjectType,
    #[serde(default)]
    pub color: GearColor,
    #[serde(default)]
    pub defective: bool,
}

/// Typed payload for CLEAR_WORKSPACE command
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct ClearWorkspacePayload {
}

/// Typed payload for PICK_AND_PLACE_TARGET command
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PickAndPlaceTargetPayload {
    pub pick_x: f64,
    pub pick_y: f64,
    pub pick_z: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drop_x: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drop_y: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drop_z: Option<f64>,
}

/// End-effector dexterous palm pneumatic actuation and grasp status
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct PalmState {
    #[serde(default)]
    pub is_grasped: bool,
}

/// Edge AI inference latency and object classification metrics
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InferenceMetrics {
    pub latency_ms: f64,
    pub confidence: f64,
    pub detected_object: String,
}

/// Single gear with id and Cartesian coordinates in robot base frame
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GearEntry {
    pub id: String,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin_x: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin_y: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin_z: Option<f64>,
    #[serde(default)]
    pub color: GearColor,
    #[serde(default)]
    pub defective: bool,
}

/// Authoritative workcell gear snapshot: spawned, in-progress, and processed buckets plus active gear id
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkcellState {
    pub spawned: Vec<GearEntry>,
    pub in_progress: Vec<GearEntry>,
    pub processed: Vec<GearEntry>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_id: Option<String>,
}

/// Canonical schema for structured error frames returned by Gateway over WebSocket
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ErrorFrame {
    pub r#type: String,
    pub error_code: String,
    pub message: String,
    pub timestamp_ns: u64,
}

impl ErrorFrame {
    #[must_use]
    pub fn new(error_code: impl Into<String>, message: impl Into<String>, timestamp_ns: u64) -> Self {
        Self {
            r#type: "ERROR".to_string(),
            error_code: error_code.into(),
            message: message.into(),
            timestamp_ns,
        }
    }
}

/// Canonical schema for inbound commands sent to EdgeNode over WebSocket or DataFabric
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RobotCommand {
    pub command_id: String,
    pub sender_id: String,
    pub timestamp_ns: u64,
    pub r#type: CommandType,
    pub payload: serde_json::Value,
}

/// Canonical schema for outbound telemetry events emitted by EdgeNode over DataFabric and WebSocket
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RobotTelemetryEvent {
    pub timestamp_ns: u64,
    pub robot_state: RobotState,
    #[serde(deserialize_with = "deserialize_finite_joints")]
    pub joint_positions: ArmJointPositions,
    #[serde(default)]
    pub palm_state: PalmState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inference_metrics: Option<InferenceMetrics>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_id: Option<String>,
    pub workcell_state: WorkcellState,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
}

impl RobotTelemetryEvent {
    /// Validates domain invariants (e.g., all joint positions are finite numbers).
    ///
    /// # Errors
    /// Returns [`DomainError::InvalidJointPositions`] if any joint position is non-finite (NaN or Inf).
    pub fn validate(&self) -> Result<(), DomainError> {
        validate_joint_positions(&self.joint_positions)
    }
}

/// Validates that a robot identifier is structurally valid.
fn validate_robot_id(robot_id: &str) -> Result<(), DomainError> {
    if robot_id.is_empty() || robot_id.contains('/') || robot_id.contains('\\') || robot_id.contains(' ') {
        return Err(DomainError::InvalidRobotId);
    }
    Ok(())
}

/// Returns the locked DataFabric command key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_command_topic(robot_id: &str) -> Result<String, DomainError> {
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{robot_id}/command"))
}

/// Returns the locked DataFabric telemetry key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_telemetry_topic(robot_id: &str) -> Result<String, DomainError> {
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{robot_id}/telemetry"))
}

/// Parses a DataFabric key expression into robot ID and channel.
#[must_use]
pub fn parse_robot_topic(topic: &str) -> Option<(String, &'static str)> {
    let parts: Vec<&str> = topic.split('/').collect();
    if parts.len() != 3 || parts[0] != "robot" || parts[1].is_empty() {
        return None;
    }

    match parts[2] {
        "command" => Some((parts[1].to_string(), "command")),
        "telemetry" => Some((parts[1].to_string(), "telemetry")),
        _ => None,
    }
}

/// Canonical UR5e joint postures in radians
#[allow(clippy::approx_constant)]
pub const CANONICAL_POSE_HOME: ArmJointPositions = [0.0, -1.5708, 0.0, -1.5708, 0.0, 0.0];
#[allow(clippy::approx_constant)]
pub const CANONICAL_POSE_READY: ArmJointPositions = [0.0, -0.7854, 1.5708, -0.7854, -1.5708, 0.0];
#[allow(clippy::approx_constant)]
pub const CANONICAL_POSE_INSPECT_POSE: ArmJointPositions = [0.0, -1.0472, 1.3963, -1.9198, -1.5708, 0.0];

/// Returns the canonical joint positions for a pre-defined posture.
#[must_use]
pub const fn canonical_pose(pose: PoseName) -> ArmJointPositions {
    match pose {
        PoseName::Home => CANONICAL_POSE_HOME,
        PoseName::Ready => CANONICAL_POSE_READY,
        PoseName::InspectPose => CANONICAL_POSE_INSPECT_POSE,
    }
}
