# Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
"""Domain schemas and DataFabric topic contracts for EdgeNode."""

from enum import Enum
from typing import Annotated, Any, Literal, Optional
from pydantic import BaseModel, ConfigDict, Field


class PalmAction(str, Enum):
    """Actuation action to execute on dexterous palm"""

    GRASP = "GRASP"
    RELEASE = "RELEASE"


class PoseName(str, Enum):
    """Pre-defined canonical UR5e posture"""

    HOME = "HOME"
    READY = "READY"
    INSPECT_POSE = "INSPECT_POSE"


class SpawnObjectType(str, Enum):
    """Type of object to spawn"""

    GEAR = "GEAR"


class CommandType(str, Enum):
    """Operational command type"""

    PING = "PING"
    TELEOP_JOINT_TARGET = "TELEOP_JOINT_TARGET"
    PALM_ACTUATE = "PALM_ACTUATE"
    TRAJECTORY_EXECUTE = "TRAJECTORY_EXECUTE"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    RESET_FAULT = "RESET_FAULT"
    ENGAGE = "ENGAGE"
    STANDBY = "STANDBY"
    SPAWN_OBJECT = "SPAWN_OBJECT"
    CLEAR_WORKSPACE = "CLEAR_WORKSPACE"
    PICK_AND_PLACE_TARGET = "PICK_AND_PLACE_TARGET"


class RobotState(str, Enum):
    """Current lifecycle state of the robotic manipulator"""

    BOOTING = "BOOTING"
    STANDBY = "STANDBY"
    IDLE = "IDLE"
    PROCESSING = "PROCESSING"
    EXECUTING = "EXECUTING"
    FAULT = "FAULT"


UR5E_JOINTS: list[str] = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

CANONICAL_UR5E_JOINTS: list[str] = UR5E_JOINTS

UR5eJoint = Literal[
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]

DEFAULT_ROBOT_ID: str = "arm-ur5"


FiniteFloat = Annotated[float, Field(allow_inf_nan=False)]
ArmJointPositions = Annotated[list[FiniteFloat], Field(min_length=6, max_length=6, description="UR5e 6-DoF joint angles in radians")]


CANONICAL_POSES: dict[PoseName, ArmJointPositions] = {
    PoseName.HOME: [0.0, -1.5708, 0.0, -1.5708, 0.0, 0.0],
    PoseName.READY: [0.0, -0.7854, 1.5708, -0.7854, -1.5708, 0.0],
    PoseName.INSPECT_POSE: [0.0, -1.0472, 1.3963, -1.9198, -1.5708, 0.0],
}


class PalmActuatePayload(BaseModel):
    """Typed payload for PALM_ACTUATE command to toggle suction or grasp status"""

    model_config = ConfigDict(extra="forbid")

    action: PalmAction = Field(..., description="Actuation action to execute on dexterous palm")


class TrajectoryExecutePayload(BaseModel):
    """Typed payload for TRAJECTORY_EXECUTE command dispatching canned or custom trajectories"""

    model_config = ConfigDict(extra="forbid")

    pose_name: Optional[PoseName] = Field(default=None, description="Pre-defined canonical UR5e posture")
    waypoints: Optional[list[ArmJointPositions]] = Field(default=None, description="Optional sequence of waypoints for custom trajectory execution")


class EmergencyStopPayload(BaseModel):
    """Typed payload for EMERGENCY_STOP command"""

    model_config = ConfigDict(extra="forbid")

    reason: Optional[str] = Field(default=None, description="Optional human-readable reason for emergency stop")


class ResetFaultPayload(BaseModel):
    """Typed payload for RESET_FAULT command"""

    model_config = ConfigDict(extra="forbid")



class EngagePayload(BaseModel):
    """Typed payload for ENGAGE command activating EdgeNode from STANDBY"""

    model_config = ConfigDict(extra="forbid")



class StandbyPayload(BaseModel):
    """Typed payload for STANDBY command parking EdgeNode to idle"""

    model_config = ConfigDict(extra="forbid")



class SpawnObjectPayload(BaseModel):
    """Typed payload for SPAWN_OBJECT command"""

    model_config = ConfigDict(extra="forbid")

    x: float = Field(..., description="Cartesian X in meters (REP-103 robot base frame)")
    y: float = Field(..., description="Cartesian Y in meters (REP-103 robot base frame)")
    z: float = Field(..., description="Cartesian Z in meters (clamped to table surface 0.0m)")
    object_type: SpawnObjectType = Field(..., description="Type of object to spawn")


class ClearWorkspacePayload(BaseModel):
    """Typed payload for CLEAR_WORKSPACE command"""

    model_config = ConfigDict(extra="forbid")



class PickAndPlaceTargetPayload(BaseModel):
    """Typed payload for PICK_AND_PLACE_TARGET command"""

    model_config = ConfigDict(extra="forbid")

    pick_x: float = Field(..., description="Cartesian X pick coordinate in robot base frame")
    pick_y: float = Field(..., description="Cartesian Y pick coordinate in robot base frame")
    pick_z: float = Field(..., description="Cartesian Z pick coordinate in robot base frame")
    drop_x: Optional[float] = Field(default=None, description="Optional custom Cartesian X drop target coordinate")
    drop_y: Optional[float] = Field(default=None, description="Optional custom Cartesian Y drop target coordinate")
    drop_z: Optional[float] = Field(default=None, description="Optional custom Cartesian Z drop target coordinate")


class PalmState(BaseModel):
    """End-effector dexterous palm pneumatic actuation and grasp status"""

    model_config = ConfigDict(extra="forbid")

    is_grasped: bool = Field(default=False, description="True if suction or grasp is actively engaged, false otherwise")


class InferenceMetrics(BaseModel):
    """Edge AI inference latency and object classification metrics"""

    model_config = ConfigDict(extra="forbid")

    latency_ms: float = Field(..., ge=0.0, description="Inference compute latency in milliseconds")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Classification detection confidence score")
    detected_object: str = Field(..., min_length=1, description="Detected object class label")


class ErrorFrame(BaseModel):
    """Canonical schema for structured error frames returned by Gateway over WebSocket"""

    model_config = ConfigDict(extra="forbid")

    type: Literal["ERROR"] = "ERROR"
    error_code: str = Field(..., min_length=1, description="Structured diagnostic error code")
    message: str = Field(..., min_length=1, description="Human-readable diagnostic error description")
    timestamp_ns: int = Field(..., ge=0, description="Nanoseconds since Unix epoch when error was generated")


class RobotCommand(BaseModel):
    """Canonical schema for inbound commands sent to EdgeNode over WebSocket or DataFabric"""

    model_config = ConfigDict(extra="forbid")

    command_id: str = Field(..., description="Unique UUID v4 identifying the command")
    sender_id: str = Field(..., min_length=1, description="Identifier of the originating sender")
    timestamp_ns: int = Field(..., ge=0, description="Nanoseconds since Unix epoch when command was dispatched")
    type: CommandType = Field(..., description="Operational command type")
    payload: dict[str, Any] = Field(default_factory=dict, description="Command-specific payload arguments")


class RobotTelemetryEvent(BaseModel):
    """Canonical schema for outbound telemetry events emitted by EdgeNode over DataFabric and WebSocket"""

    model_config = ConfigDict(extra="forbid")

    timestamp_ns: int = Field(..., ge=0, description="Nanoseconds since Unix epoch when telemetry state was sampled")
    robot_state: RobotState = Field(..., description="Current lifecycle state of the robotic manipulator")
    joint_positions: ArmJointPositions
    palm_state: PalmState = Field(default_factory=PalmState, description="End-effector dexterous palm pneumatic actuation and grasp status")
    inference_metrics: Optional[InferenceMetrics] = Field(default=None, description="Edge AI inference latency and object classification metrics")
    command_id: Optional[str] = Field(default=None, description="Optional command identifier acknowledged by this telemetry event")


def _validate_robot_id(robot_id: str) -> None:
    if not robot_id or "/" in robot_id or "\\" in robot_id or " " in robot_id:
        raise ValueError(f"Invalid robot ID '{robot_id}': must be non-empty and not contain slashes or whitespace")


def robot_command_topic(robot_id: str) -> str:
    """Returns the locked DataFabric command key expression for a robot."""
    _validate_robot_id(robot_id)
    return f"robot/{robot_id}/command"


def robot_telemetry_topic(robot_id: str) -> str:
    """Returns the locked DataFabric telemetry key expression for a robot."""
    _validate_robot_id(robot_id)
    return f"robot/{robot_id}/telemetry"


def parse_robot_topic(topic: str) -> tuple[str, str] | None:
    """Parses a DataFabric key expression into (robot_id, channel) or returns None if invalid."""
    parts = topic.split("/")
    if len(parts) != 3 or parts[0] != "robot" or not parts[1]:
        return None
    if parts[2] not in ("command", "telemetry"):
        return None
    return (parts[1], parts[2])
