// Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
use serde::{Deserialize, Deserializer, Serialize};
use thiserror::Error;

/// Error types encountered in domain validation and key resolution.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DomainError {
    #[error("Invalid robot ID: must be non-empty and not contain slashes")]
    InvalidRobotId,
    #[error("Invalid joint positions: must contain finite float values")]
    InvalidJointPositions,
}

/// Operational command type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommandType {
    Ping,
    TeleopJointTarget,
    TrajectoryExecute,
    EmergencyStop,
    ResetFault,
}

/// Current lifecycle state of the robotic manipulator
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RobotState {
    Booting,
    Idle,
    Processing,
    Executing,
    Fault,
}

/// Canonical UR5e 6-DoF joint names in kinematic sequence
pub const UR5E_JOINTS: [&str; 6] = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
];

/// Alias for canonical joint names.
pub const CANONICAL_UR5E_JOINTS: [&str; 6] = UR5E_JOINTS;

/// Canonical default robot identifier across all services
pub const DEFAULT_ROBOT_ID: &str = "arm-ur5";

/// Array of exactly 6 joint positions in radians.
pub type ArmJointPositions = [f64; 6];

fn deserialize_finite_joints<'de, D>(deserializer: D) -> Result<ArmJointPositions, D::Error>
where
    D: Deserializer<'de>,
{
    let arr = <ArmJointPositions>::deserialize(deserializer)?;
    for (idx, &val) in arr.iter().enumerate() {
        if !val.is_finite() {
            return Err(serde::de::Error::custom(format!(
                "Joint position at index {idx} must be a finite number"
            )));
        }
    }
    Ok(arr)
}

/// Validates that an array of joint positions contains only finite floats.
///
/// # Errors
/// Returns [`DomainError::InvalidJointPositions`] if any joint position is non-finite (NaN or Inf).
pub fn validate_joint_positions(joint_positions: &ArmJointPositions) -> Result<(), DomainError> {
    if !joint_positions.iter().all(|&p| p.is_finite()) {
        return Err(DomainError::InvalidJointPositions);
    }
    Ok(())
}

/// Edge AI inference latency and object classification metrics
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InferenceMetrics {
    pub latency_ms: f64,
    pub confidence: f64,
    pub detected_object: String,
}

/// Canonical schema for structured error frames returned by Gateway over WebSocket
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorFrame {
    pub r#type: String,
    pub error_code: String,
    pub message: String,
    pub timestamp_ns: u64,
}

impl ErrorFrame {
    #[must_use]
    pub fn new(error_code: impl Into<String>, message: impl Into<String>, timestamp_ns: u64) -> Self {
        Self {
            r#type: "ERROR".to_string(),
            error_code: error_code.into(),
            message: message.into(),
            timestamp_ns,
        }
    }
}

/// Canonical schema for inbound commands sent to EdgeNode over WebSocket or DataFabric
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RobotCommand {
    pub command_id: String,
    pub sender_id: String,
    pub timestamp_ns: u64,
    pub r#type: CommandType,
    pub payload: serde_json::Value,
}

/// Canonical schema for outbound telemetry events emitted by EdgeNode over DataFabric and WebSocket
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RobotTelemetryEvent {
    pub timestamp_ns: u64,
    pub robot_state: RobotState,
    #[serde(deserialize_with = "deserialize_finite_joints")]
    pub joint_positions: ArmJointPositions,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inference_metrics: Option<InferenceMetrics>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_id: Option<String>,
}

impl RobotTelemetryEvent {
    /// Validates domain invariants (e.g., all joint positions are finite numbers).
    ///
    /// # Errors
    /// Returns [`DomainError::InvalidJointPositions`] if any joint position is non-finite (NaN or Inf).
    pub fn validate(&self) -> Result<(), DomainError> {
        validate_joint_positions(&self.joint_positions)
    }
}

/// Validates that a robot identifier is structurally valid.
fn validate_robot_id(robot_id: &str) -> Result<(), DomainError> {
    if robot_id.is_empty() || robot_id.contains('/') || robot_id.contains('\\') || robot_id.contains(' ') {
        return Err(DomainError::InvalidRobotId);
    }
    Ok(())
}

/// Returns the locked DataFabric command key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_command_topic(robot_id: &str) -> Result<String, DomainError> {
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{robot_id}/command"))
}

/// Returns the locked DataFabric telemetry key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_telemetry_topic(robot_id: &str) -> Result<String, DomainError> {
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{robot_id}/telemetry"))
}

/// Parses a DataFabric key expression into robot ID and channel.
#[must_use]
pub fn parse_robot_topic(topic: &str) -> Option<(String, &'static str)> {
    let parts: Vec<&str> = topic.split('/').collect();
    if parts.len() != 3 || parts[0] != "robot" || parts[1].is_empty() {
        return None;
    }

    match parts[2] {
        "command" => Some((parts[1].to_string(), "command")),
        "telemetry" => Some((parts[1].to_string(), "telemetry")),
        _ => None,
    }
}
