"""Backward-compat shim; implementation lives in `kinematics/` package."""

from arm_controller.kinematics import *  # noqa: F401,F403
from arm_controller.kinematics import (
    APPROACH_LIFT_OFFSET_M,
    CANONICAL_UR5E_JOINTS,
    DEFAULT_DOWNWARD_ORIENTATION,
    DEFAULT_SPINDLE_TOWER_COORDS,
    DEFAULT_TCP_OFFSET_M,
    HOME_JOINT_POSITIONS,
    INSPECT_JOINT_POSITIONS,
    MAX_REACH_M,
    MIN_REACH_M,
    READY_JOINT_POSITIONS,
    UR5E_DH_A,
    UR5E_DH_ALPHA,
    UR5E_DH_D,
    ActionPhase,
    AnalyticalInverseKinematics,
    KinematicSingularityError,
    KinematicsError,
    OutOfReachError,
    PickAndPlaceTrajectoryGenerator,
    UnreachableTargetError,
    UR5eKinematics,
    WaypointStep,
    normalize_angle,
    unwrap_joint_angles,
)

__all__ = [
    "APPROACH_LIFT_OFFSET_M",
    "ActionPhase",
    "AnalyticalInverseKinematics",
    "CANONICAL_UR5E_JOINTS",
    "DEFAULT_DOWNWARD_ORIENTATION",
    "DEFAULT_SPINDLE_TOWER_COORDS",
    "DEFAULT_TCP_OFFSET_M",
    "HOME_JOINT_POSITIONS",
    "INSPECT_JOINT_POSITIONS",
    "KinematicSingularityError",
    "KinematicsError",
    "MAX_REACH_M",
    "MIN_REACH_M",
    "OutOfReachError",
    "PickAndPlaceTrajectoryGenerator",
    "READY_JOINT_POSITIONS",
    "UnreachableTargetError",
    "UR5eKinematics",
    "UR5E_DH_A",
    "UR5E_DH_ALPHA",
    "UR5E_DH_D",
    "WaypointStep",
    "normalize_angle",
    "unwrap_joint_angles",
]
