#!/usr/bin/env python3
"""Generate domain models for Rust, Python, and TypeScript from canonical JSON schemas."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def to_pascal_case(s: str) -> str:
    return "".join(word.capitalize() for word in s.split("_"))


def load_schemas(schemas_dir: Path) -> tuple[dict, dict, dict]:
    with open(schemas_dir / "robot_command.schema.json", "r", encoding="utf-8") as f:
        cmd_schema = json.load(f)
    with open(schemas_dir / "robot_telemetry_event.schema.json", "r", encoding="utf-8") as f:
        telem_schema = json.load(f)
    with open(schemas_dir / "error_frame.schema.json", "r", encoding="utf-8") as f:
        err_schema = json.load(f)
    return cmd_schema, telem_schema, err_schema


def generate_rust(cmd_schema: dict, telem_schema: dict, _err_schema: dict) -> str:
    cmd_enums = cmd_schema["properties"]["type"]["enum"]
    robot_states = telem_schema["properties"]["robot_state"]["enum"]
    joint_count = telem_schema["properties"]["joint_positions"]["minItems"]

    rust_cmd_variants = "\n".join(f"    {to_pascal_case(v)}," for v in cmd_enums)
    rust_state_variants = "\n".join(f"    {to_pascal_case(v)}," for v in robot_states)

    return f"""// Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
use serde::{{Deserialize, Serialize}};
use thiserror::Error;

/// Error types encountered in domain validation and key resolution.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum DomainError {{
    #[error("Invalid robot ID: must be non-empty and not contain slashes")]
    InvalidRobotId,
}}

/// Permitted operational command types for the EdgeNode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommandType {{
{rust_cmd_variants}
}}

/// Operational lifecycle state of the robotic manipulator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RobotState {{
{rust_state_variants}
}}

/// Inference performance and classification metrics from Edge AI models.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InferenceMetrics {{
    pub latency_ms: f64,
    pub confidence: f64,
    pub detected_object: String,
}}

/// Structured inbound instruction sent to EdgeNode.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RobotCommand {{
    pub command_id: String,
    pub sender_id: String,
    pub timestamp_ns: u64,
    pub r#type: CommandType,
    pub payload: serde_json::Value,
}}

/// Structured domain event emitted by EdgeNode.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RobotTelemetryEvent {{
    pub timestamp_ns: u64,
    pub robot_state: RobotState,
    pub joint_positions: [f64; {joint_count}],
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inference_metrics: Option<InferenceMetrics>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_id: Option<String>,
}}

/// Structured error message sent by Gateway on schema or validation errors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorFrame {{
    pub r#type: String,
    pub error_code: String,
    pub message: String,
    pub timestamp_ns: u64,
}}

impl ErrorFrame {{
    #[must_use]
    pub fn new(error_code: impl Into<String>, message: impl Into<String>, timestamp_ns: u64) -> Self {{
        Self {{
            r#type: "ERROR".to_string(),
            error_code: error_code.into(),
            message: message.into(),
            timestamp_ns,
        }}
    }}
}}

/// Validates that a robot identifier is structurally valid.
fn validate_robot_id(robot_id: &str) -> Result<(), DomainError> {{
    if robot_id.is_empty() || robot_id.contains('/') || robot_id.contains('\\\\') || robot_id.contains(' ') {{
        return Err(DomainError::InvalidRobotId);
    }}
    Ok(())
}}

/// Returns the locked DataFabric command key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_command_topic(robot_id: &str) -> Result<String, DomainError> {{
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{{robot_id}}/command"))
}}

/// Returns the locked DataFabric telemetry key expression for a robot.
///
/// # Errors
/// Returns [`DomainError::InvalidRobotId`] if `robot_id` is empty or contains path delimiters.
pub fn robot_telemetry_topic(robot_id: &str) -> Result<String, DomainError> {{
    validate_robot_id(robot_id)?;
    Ok(format!("robot/{{robot_id}}/telemetry"))
}}

/// Parses a DataFabric key expression into robot ID and channel.
#[must_use]
pub fn parse_robot_topic(topic: &str) -> Option<(String, &'static str)> {{
    let parts: Vec<&str> = topic.split('/').collect();
    if parts.len() != 3 || parts[0] != "robot" || parts[1].is_empty() {{
        return None;
    }}

    match parts[2] {{
        "command" => Some((parts[1].to_string(), "command")),
        "telemetry" => Some((parts[1].to_string(), "telemetry")),
        _ => None,
    }}
}}
"""


def generate_python(cmd_schema: dict, telem_schema: dict, _err_schema: dict) -> str:
    cmd_enums = cmd_schema["properties"]["type"]["enum"]
    robot_states = telem_schema["properties"]["robot_state"]["enum"]
    joint_count = telem_schema["properties"]["joint_positions"]["minItems"]

    py_cmd_variants = "\n".join(f'    {v} = "{v}"' for v in cmd_enums)
    py_state_variants = "\n".join(f'    {v} = "{v}"' for v in robot_states)

    return f'''# Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
"""Domain schemas and DataFabric topic contracts for EdgeNode."""

from enum import Enum
from typing import Annotated, Any, Literal, Optional
from pydantic import BaseModel, ConfigDict, Field


class CommandType(str, Enum):
    """Permitted operational command types for the EdgeNode."""

{py_cmd_variants}


class RobotState(str, Enum):
    """Operational lifecycle state of the robotic manipulator."""

{py_state_variants}


class InferenceMetrics(BaseModel):
    """Inference performance and classification metrics from Edge AI models."""

    model_config = ConfigDict(extra="forbid")

    latency_ms: float = Field(..., ge=0.0, description="Inference compute latency in milliseconds")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence score")
    detected_object: str = Field(..., min_length=1, description="Detected object class label")


class RobotCommand(BaseModel):
    """Structured inbound instruction sent to EdgeNode."""

    model_config = ConfigDict(extra="forbid")

    command_id: str = Field(..., min_length=1, description="Command UUID v4")
    sender_id: str = Field(..., min_length=1, description="Sender component identifier")
    timestamp_ns: int = Field(..., ge=0, description="Timestamp in nanoseconds since epoch")
    type: CommandType = Field(..., description="Operational command enum")
    payload: dict[str, Any] = Field(default_factory=dict, description="Command-specific payload object")


class RobotTelemetryEvent(BaseModel):
    """Structured domain event emitted by EdgeNode."""

    model_config = ConfigDict(extra="forbid")

    timestamp_ns: int = Field(..., ge=0, description="Timestamp in nanoseconds since epoch")
    robot_state: RobotState = Field(..., description="Operational lifecycle state")
    joint_positions: Annotated[list[float], Field(..., min_length={joint_count}, max_length={joint_count}, description="UR5e 6-DoF joint angles in radians")]
    inference_metrics: Optional[InferenceMetrics] = Field(default=None, description="Optional Edge AI detection metrics")
    command_id: Optional[str] = Field(default=None, description="Optional command acknowledgment ID")


class ErrorFrame(BaseModel):
    """Structured error message sent by Gateway on schema or validation errors."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["ERROR"] = "ERROR"
    error_code: str = Field(..., min_length=1, description="Diagnostic error code")
    message: str = Field(..., min_length=1, description="Diagnostic error message")
    timestamp_ns: int = Field(..., ge=0, description="Timestamp in nanoseconds since epoch")


def _validate_robot_id(robot_id: str) -> None:
    if not robot_id or "/" in robot_id or "\\\\" in robot_id or " " in robot_id:
        raise ValueError(f"Invalid robot ID '{{robot_id}}': must be non-empty and not contain slashes or whitespace")


def robot_command_topic(robot_id: str) -> str:
    """Returns the locked DataFabric command key expression for a robot."""
    _validate_robot_id(robot_id)
    return f"robot/{{robot_id}}/command"


def robot_telemetry_topic(robot_id: str) -> str:
    """Returns the locked DataFabric telemetry key expression for a robot."""
    _validate_robot_id(robot_id)
    return f"robot/{{robot_id}}/telemetry"


def parse_robot_topic(topic: str) -> tuple[str, str] | None:
    """Parses a DataFabric key expression into (robot_id, channel) or returns None if invalid."""
    parts = topic.split("/")
    if len(parts) != 3 or parts[0] != "robot" or not parts[1]:
        return None
    if parts[2] not in ("command", "telemetry"):
        return None
    return (parts[1], parts[2])
'''


def generate_typescript(cmd_schema: dict, telem_schema: dict, _err_schema: dict) -> str:
    cmd_enums = cmd_schema["properties"]["type"]["enum"]
    robot_states = telem_schema["properties"]["robot_state"]["enum"]
    joint_count = telem_schema["properties"]["joint_positions"]["minItems"]

    ts_cmd_variants = "\n".join(f"  {v}: '{v}'," for v in cmd_enums)
    ts_state_variants = "\n".join(f"  {v}: '{v}'," for v in robot_states)
    ts_joint_types = ", ".join(["number"] * joint_count)

    return f"""// Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
/**
 * Domain schemas and DataFabric topic contracts for Web Visualizer & TeleopClient.
 */

export const CommandType = {{
{ts_cmd_variants}
}} as const;

export type CommandType = (typeof CommandType)[keyof typeof CommandType];

export const RobotState = {{
{ts_state_variants}
}} as const;

export type RobotState = (typeof RobotState)[keyof typeof RobotState];

export type ArmJointPositions = [{ts_joint_types}];

export interface InferenceMetrics {{
  latency_ms: number;
  confidence: number;
  detected_object: string;
}}

export interface RobotCommand {{
  command_id: string;
  sender_id: string;
  timestamp_ns: string | number | bigint;
  type: CommandType;
  payload: Record<string, unknown>;
}}

export interface RobotTelemetryEvent {{
  timestamp_ns: string | number | bigint;
  robot_state: RobotState;
  joint_positions: ArmJointPositions;
  inference_metrics?: InferenceMetrics;
  command_id?: string;
}}

export interface ErrorFrame {{
  type: 'ERROR';
  error_code: string;
  message: string;
  timestamp_ns: string | number | bigint;
}}

export function createPingCommand(params?: {{
  senderId?: string;
  commandId?: string;
  timestampNs?: bigint | number;
}}): RobotCommand {{
  return {{
    command_id: params?.commandId ?? (typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `cmd-${{Date.now()}}`),
    sender_id: params?.senderId ?? 'teleop-ui',
    timestamp_ns: params?.timestampNs ?? BigInt(Date.now()) * 1_000_000n,
    type: CommandType.PING,
    payload: {{}},
  }};
}}

function parseJsonIfNeeded(input: string | unknown): unknown {{
  if (typeof input === 'string') {{
    return JSON.parse(input);
  }}
  return input;
}}

export function parseRobotCommand(input: string | unknown): RobotCommand {{
  const data = parseJsonIfNeeded(input);
  if (!data || typeof data !== 'object') {{
    throw new Error('RobotCommand payload must be an object');
  }}

  const obj = data as Record<string, unknown>;
  if (typeof obj.command_id !== 'string' || !obj.command_id) {{
    throw new Error("Missing required field 'command_id'");
  }}
  if (typeof obj.sender_id !== 'string' || !obj.sender_id) {{
    throw new Error("Missing required field 'sender_id'");
  }}
  if (obj.timestamp_ns === undefined || obj.timestamp_ns === null) {{
    throw new Error("Missing required field 'timestamp_ns'");
  }}

  const validTypes = Object.values(CommandType) as string[];
  if (typeof obj.type !== 'string' || !validTypes.includes(obj.type)) {{
    throw new Error(`Invalid command type: ${{String(obj.type)}}`);
  }}

  if (obj.payload === undefined || obj.payload === null || typeof obj.payload !== 'object' || Array.isArray(obj.payload)) {{
    throw new Error("Missing or invalid 'payload' object");
  }}

  return {{
    command_id: obj.command_id,
    sender_id: obj.sender_id,
    timestamp_ns: obj.timestamp_ns as string | number | bigint,
    type: obj.type as CommandType,
    payload: obj.payload as Record<string, unknown>,
  }};
}}

export function parseRobotTelemetryEvent(input: string | unknown): RobotTelemetryEvent {{
  const data = parseJsonIfNeeded(input);
  if (!data || typeof data !== 'object') {{
    throw new Error('RobotTelemetryEvent payload must be an object');
  }}

  const obj = data as Record<string, unknown>;
  if (obj.timestamp_ns === undefined || obj.timestamp_ns === null) {{
    throw new Error("Missing required field 'timestamp_ns'");
  }}

  const validStates = Object.values(RobotState) as string[];
  if (typeof obj.robot_state !== 'string' || !validStates.includes(obj.robot_state)) {{
    throw new Error(`Invalid robot state: ${{String(obj.robot_state)}}`);
  }}

  if (!Array.isArray(obj.joint_positions) || obj.joint_positions.length !== {joint_count}) {{
    throw new Error(
      `RobotTelemetryEvent must contain exactly {joint_count} joint positions, received ${{Array.isArray(obj.joint_positions) ? obj.joint_positions.length : 'non-array'}}`
    );
  }}

  for (let i = 0; i < {joint_count}; i++) {{
    if (typeof obj.joint_positions[i] !== 'number' || Number.isNaN(obj.joint_positions[i])) {{
      throw new Error(`Joint position at index ${{i}} is not a valid number`);
    }}
  }}

  let inference_metrics: InferenceMetrics | undefined;
  if (obj.inference_metrics && typeof obj.inference_metrics === 'object') {{
    const im = obj.inference_metrics as Record<string, unknown>;
    if (
      typeof im.latency_ms === 'number' &&
      typeof im.confidence === 'number' &&
      typeof im.detected_object === 'string'
    ) {{
      inference_metrics = {{
        latency_ms: im.latency_ms,
        confidence: im.confidence,
        detected_object: im.detected_object,
      }};
    }}
  }}

  return {{
    timestamp_ns: obj.timestamp_ns as string | number | bigint,
    robot_state: obj.robot_state as RobotState,
    joint_positions: obj.joint_positions as ArmJointPositions,
    inference_metrics,
    command_id: typeof obj.command_id === 'string' ? obj.command_id : undefined,
  }};
}}

export function parseErrorFrame(input: string | unknown): ErrorFrame {{
  const data = parseJsonIfNeeded(input);
  if (!data || typeof data !== 'object') {{
    throw new Error('ErrorFrame payload must be an object');
  }}

  const obj = data as Record<string, unknown>;
  if (obj.type !== 'ERROR') {{
    throw new Error(`Expected frame type 'ERROR', got '${{String(obj.type)}}'`);
  }}
  if (typeof obj.error_code !== 'string' || !obj.error_code) {{
    throw new Error("Missing required field 'error_code'");
  }}
  if (typeof obj.message !== 'string' || !obj.message) {{
    throw new Error("Missing required field 'message'");
  }}
  if (obj.timestamp_ns === undefined || obj.timestamp_ns === null) {{
    throw new Error("Missing required field 'timestamp_ns'");
  }}

  return {{
    type: 'ERROR',
    error_code: obj.error_code,
    message: obj.message,
    timestamp_ns: obj.timestamp_ns as string | number | bigint,
  }};
}}

function validateRobotId(robotId: string): void {{
  if (!robotId || robotId.includes('/') || robotId.includes('\\\\') || robotId.includes(' ')) {{
    throw new Error(`Invalid robot ID '${{robotId}}': must be non-empty and not contain slashes or whitespace`);
  }}
}}

export function robotCommandTopic(robotId: string): string {{
  validateRobotId(robotId);
  return `robot/${{robotId}}/command`;
}}

export function robotTelemetryTopic(robotId: string): string {{
  validateRobotId(robotId);
  return `robot/${{robotId}}/telemetry`;
}}

export function parseRobotTopic(
  topic: string
): {{ robotId: string; channel: 'command' | 'telemetry' }} | null {{
  const parts = topic.split('/');
  if (parts.length !== 3 || parts[0] !== 'robot' || !parts[1]) {{
    return null;
  }}
  if (parts[2] !== 'command' && parts[2] !== 'telemetry') {{
    return null;
  }}
  return {{
    robotId: parts[1],
    channel: parts[2],
  }};
}}

export function serializeCommand(cmd: RobotCommand): string {{
  return JSON.stringify(cmd, (_, v) =>
    typeof v === 'bigint' ? Number(v) : v
  );
}}

export function isRobotTelemetryEvent(input: unknown): input is RobotTelemetryEvent {{
  try {{
    parseRobotTelemetryEvent(input);
    return true;
  }} catch {{
    return false;
  }}
}}

export function isErrorFrame(input: unknown): input is ErrorFrame {{
  try {{
    parseErrorFrame(input);
    return true;
  }} catch {{
    return false;
  }}
}}

export function isRobotCommand(input: unknown): input is RobotCommand {{
  try {{
    parseRobotCommand(input);
    return true;
  }} catch {{
    return false;
  }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate domain models from JSON schemas")
    parser.add_argument("--check", action="store_true", help="Verify generated files match without writing")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    schemas_dir = repo_root / "schemas"

    rust_target = repo_root / "src" / "domain" / "domain.rs"
    py_target = repo_root / "src" / "domain" / "domain.py"
    ts_target = repo_root / "web" / "domain" / "contracts.ts"

    cmd_schema, telem_schema, err_schema = load_schemas(schemas_dir)

    rust_content = generate_rust(cmd_schema, telem_schema, err_schema)
    py_content = generate_python(cmd_schema, telem_schema, err_schema)
    ts_content = generate_typescript(cmd_schema, telem_schema, err_schema)

    targets = [
        (rust_target, rust_content),
        (py_target, py_content),
        (ts_target, ts_content),
    ]

    if args.check:
        mismatched = []
        for path, expected in targets:
            if not path.exists():
                mismatched.append(f"Missing: {path}")
            else:
                actual = path.read_text(encoding="utf-8")
                if actual != expected:
                    mismatched.append(f"Drift detected in: {path}")
        if mismatched:
            for m in mismatched:
                print(m, file=sys.stderr)
            return 1
        print("All domain targets match schemas. OK.")
        return 0

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Generated {path.relative_to(repo_root)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
