// Auto-generated by scripts/generate_domain.py. DO NOT EDIT DIRECTLY.
/**
 * Domain schemas and DataFabric topic contracts for Web Visualizer & TeleopClient.
 */
import { z } from 'zod';

export const jsonInput = z.unknown().transform((val, ctx) => {
  if (typeof val === 'string') {
    try {
      return JSON.parse(val);
    } catch {
      ctx.addIssue({ code: 'custom', message: 'Payload must be valid JSON' });
      return z.NEVER;
    }
  }
  return val;
});

export const timestampNsSchema = z
  .union([z.bigint(), z.number(), z.string()], {
    message: "Missing required field 'timestamp_ns'",
  })
  .refine(
    (val) => {
      try {
        if (typeof val === 'number' && !Number.isFinite(val)) {
          return false;
        }
        const ts =
          typeof val === 'bigint'
            ? val
            : BigInt(typeof val === 'number' ? Math.floor(val) : String(val));
        return ts >= 0n;
      } catch {
        return false;
      }
    },
    { message: "Field 'timestamp_ns' must be a non-negative integer" }
  );

/** Actuation action to execute on dexterous palm */
export const PalmAction = {
  GRASP: 'GRASP',
  RELEASE: 'RELEASE',
} as const;

export const PalmActionSchema = z.enum([
  'GRASP',
  'RELEASE',
], { message: 'Invalid palm action' });

export const palmActionSchema = PalmActionSchema;

export type PalmAction = z.infer<typeof PalmActionSchema>;

/** Pre-defined canonical UR5e posture */
export const PoseName = {
  HOME: 'HOME',
  READY: 'READY',
  INSPECT_POSE: 'INSPECT_POSE',
} as const;

export const PoseNameSchema = z.enum([
  'HOME',
  'READY',
  'INSPECT_POSE',
], { message: 'Invalid pose name' });

export const poseNameSchema = PoseNameSchema;

export type PoseName = z.infer<typeof PoseNameSchema>;

/** Type of object to spawn */
export const SpawnObjectType = {
  GEAR: 'GEAR',
} as const;

export const SpawnObjectTypeSchema = z.enum([
  'GEAR',
], { message: 'Invalid spawn object type' });

export const spawnObjectTypeSchema = SpawnObjectTypeSchema;

export type SpawnObjectType = z.infer<typeof SpawnObjectTypeSchema>;

/** Operational command type */
export const CommandType = {
  PING: 'PING',
  TELEOP_JOINT_TARGET: 'TELEOP_JOINT_TARGET',
  PALM_ACTUATE: 'PALM_ACTUATE',
  TRAJECTORY_EXECUTE: 'TRAJECTORY_EXECUTE',
  EMERGENCY_STOP: 'EMERGENCY_STOP',
  RESET_FAULT: 'RESET_FAULT',
  SPAWN_OBJECT: 'SPAWN_OBJECT',
  CLEAR_WORKSPACE: 'CLEAR_WORKSPACE',
} as const;

export const CommandTypeSchema = z.enum([
  'PING',
  'TELEOP_JOINT_TARGET',
  'PALM_ACTUATE',
  'TRAJECTORY_EXECUTE',
  'EMERGENCY_STOP',
  'RESET_FAULT',
  'SPAWN_OBJECT',
  'CLEAR_WORKSPACE',
], { message: 'Invalid command type' });

export const commandTypeSchema = CommandTypeSchema;

export type CommandType = z.infer<typeof CommandTypeSchema>;

/** Current lifecycle state of the robotic manipulator */
export const RobotState = {
  BOOTING: 'BOOTING',
  IDLE: 'IDLE',
  PROCESSING: 'PROCESSING',
  EXECUTING: 'EXECUTING',
  FAULT: 'FAULT',
} as const;

export const RobotStateSchema = z.enum([
  'BOOTING',
  'IDLE',
  'PROCESSING',
  'EXECUTING',
  'FAULT',
], { message: 'Invalid robot state' });

export const robotStateSchema = RobotStateSchema;

export type RobotState = z.infer<typeof RobotStateSchema>;

/** Canonical UR5e 6-DoF joint names in kinematic sequence */
export const UR5E_JOINTS = [
  'shoulder_pan_joint',
  'shoulder_lift_joint',
  'elbow_joint',
  'wrist_1_joint',
  'wrist_2_joint',
  'wrist_3_joint',
] as const;

export const CANONICAL_UR5E_JOINTS = UR5E_JOINTS;

export const UR5eJointSchema = z.enum(UR5E_JOINTS);
export const ur5eJointSchema = UR5eJointSchema;

export type UR5eJoint = z.infer<typeof UR5eJointSchema>;

/** Canonical default robot identifier across all services */
export const DEFAULT_ROBOT_ID = 'arm-ur5';

/** UR5e 6-DoF joint angles in radians */
export type ArmJointPositions = [number, number, number, number, number, number];

export const ArmJointPositionsSchema = z
  .array(
    z.unknown().refine(
      (val): val is number => typeof val === 'number' && Number.isFinite(val),
      { message: 'Joint position is not a valid finite number' }
    )
  )
  .refine((arr): arr is ArmJointPositions => arr.length === 6, {
    message: 'ArmJointPositions must contain exactly 6 joint positions',
  });

export const armJointPositionsSchema = ArmJointPositionsSchema;

export const CANONICAL_POSES: Record<PoseName, ArmJointPositions> = {
  HOME: [0.0, -1.5708, 0.0, -1.5708, 0.0, 0.0],
  READY: [0.0, -0.7854, 1.5708, -0.7854, -1.5708, 0.0],
  INSPECT_POSE: [0.0, -1.0472, 1.3963, -1.9198, -1.5708, 0.0],
} as const;
export const jointPositionsSchema = ArmJointPositionsSchema;

/** Typed payload for PALM_ACTUATE command to toggle suction or grasp status */
export const rawPalmActuatePayloadSchema = z.object(
  {
    action: PalmActionSchema,
  },
  { message: 'PalmActuatePayload payload must be an object' }
).strict();

export const PalmActuatePayloadSchema = jsonInput.pipe(rawPalmActuatePayloadSchema);
export const palmActuatePayloadSchema = PalmActuatePayloadSchema;

export type PalmActuatePayload = z.infer<typeof rawPalmActuatePayloadSchema>;

/** Typed payload for TRAJECTORY_EXECUTE command dispatching canned or custom trajectories */
export const rawTrajectoryExecutePayloadSchema = z.object(
  {
    pose_name: PoseNameSchema.nullish(),
    waypoints: z.array(armJointPositionsSchema).nullish(),
  },
  { message: 'TrajectoryExecutePayload payload must be an object' }
).strict();

export const TrajectoryExecutePayloadSchema = jsonInput.pipe(rawTrajectoryExecutePayloadSchema);
export const trajectoryExecutePayloadSchema = TrajectoryExecutePayloadSchema;

export type TrajectoryExecutePayload = z.infer<typeof rawTrajectoryExecutePayloadSchema>;

/** Typed payload for EMERGENCY_STOP command */
export const rawEmergencyStopPayloadSchema = z.object(
  {
    reason: z.string().nullish(),
  },
  { message: 'EmergencyStopPayload payload must be an object' }
).strict();

export const EmergencyStopPayloadSchema = jsonInput.pipe(rawEmergencyStopPayloadSchema);
export const emergencyStopPayloadSchema = EmergencyStopPayloadSchema;

export type EmergencyStopPayload = z.infer<typeof rawEmergencyStopPayloadSchema>;

/** Typed payload for RESET_FAULT command */
export const rawResetFaultPayloadSchema = z.object(
  {
  },
  { message: 'ResetFaultPayload payload must be an object' }
).strict();

export const ResetFaultPayloadSchema = jsonInput.pipe(rawResetFaultPayloadSchema);
export const resetFaultPayloadSchema = ResetFaultPayloadSchema;

export type ResetFaultPayload = z.infer<typeof rawResetFaultPayloadSchema>;

/** Typed payload for SPAWN_OBJECT command */
export const rawSpawnObjectPayloadSchema = z.object(
  {
    x: z.number({ message: "Field 'x' must be a number" }),
    y: z.number({ message: "Field 'y' must be a number" }),
    z: z.number({ message: "Field 'z' must be a number" }),
    object_type: SpawnObjectTypeSchema,
  },
  { message: 'SpawnObjectPayload payload must be an object' }
).strict();

export const SpawnObjectPayloadSchema = jsonInput.pipe(rawSpawnObjectPayloadSchema);
export const spawnObjectPayloadSchema = SpawnObjectPayloadSchema;

export type SpawnObjectPayload = z.infer<typeof rawSpawnObjectPayloadSchema>;

/** Typed payload for CLEAR_WORKSPACE command */
export const rawClearWorkspacePayloadSchema = z.object(
  {
  },
  { message: 'ClearWorkspacePayload payload must be an object' }
).strict();

export const ClearWorkspacePayloadSchema = jsonInput.pipe(rawClearWorkspacePayloadSchema);
export const clearWorkspacePayloadSchema = ClearWorkspacePayloadSchema;

export type ClearWorkspacePayload = z.infer<typeof rawClearWorkspacePayloadSchema>;

/** End-effector dexterous palm pneumatic actuation and grasp status */
export const rawPalmStateSchema = z.object(
  {
    is_grasped: z.boolean().default(false),
  },
  { message: 'PalmState payload must be an object' }
).strict();

export const PalmStateSchema = jsonInput.pipe(rawPalmStateSchema);
export const palmStateSchema = PalmStateSchema;

export type PalmState = z.infer<typeof rawPalmStateSchema>;

/** Edge AI inference latency and object classification metrics */
export const rawInferenceMetricsSchema = z.object(
  {
    latency_ms: z.number({ message: "Field 'latency_ms' must be a number" }).min(0.0, { message: "Field 'latency_ms' must be non-negative" }),
    confidence: z.number({ message: "Field 'confidence' must be a number" }).min(0.0, { message: "Field 'confidence' must be between 0.0 and 1.0" }).max(1.0, { message: "Field 'confidence' must be between 0.0 and 1.0" }),
    detected_object: z.string({ message: "Missing required field 'detected_object'" }).min(1, { message: "Field 'detected_object' must be non-empty" }),
  },
  { message: 'InferenceMetrics payload must be an object' }
).strict();

export const InferenceMetricsSchema = jsonInput.pipe(rawInferenceMetricsSchema);
export const inferenceMetricsSchema = InferenceMetricsSchema;

export type InferenceMetrics = z.infer<typeof rawInferenceMetricsSchema>;

/** Canonical schema for structured error frames returned by Gateway over WebSocket */
export const rawErrorFrameSchema = z.object(
  {
    type: z.literal('ERROR', { message: "Expected frame type 'ERROR'" }),
    error_code: z.string({ message: "Missing required field 'error_code'" }).min(1, { message: "Missing required field 'error_code'" }),
    message: z.string({ message: "Missing required field 'message'" }).min(1, { message: "Missing required field 'message'" }),
    timestamp_ns: timestampNsSchema,
  },
  { message: 'ErrorFrame payload must be an object' }
).strict();

export const ErrorFrameSchema = jsonInput.pipe(rawErrorFrameSchema);
export const errorFrameSchema = ErrorFrameSchema;

export type ErrorFrame = z.infer<typeof rawErrorFrameSchema>;

/** Canonical schema for inbound commands sent to EdgeNode over WebSocket or DataFabric */
export const rawRobotCommandSchema = z.object(
  {
    command_id: z.string({ message: "Missing required field 'command_id'" }),
    sender_id: z.string({ message: "Missing required field 'sender_id'" }).min(1, { message: "Missing required field 'sender_id'" }),
    timestamp_ns: timestampNsSchema,
    type: CommandTypeSchema,
    payload: z.record(z.string(), z.unknown(), { message: "Missing or invalid 'payload' object" }),
  },
  { message: 'RobotCommand payload must be an object' }
).strict();

export const RobotCommandSchema = jsonInput.pipe(rawRobotCommandSchema);
export const robotCommandSchema = RobotCommandSchema;

export type RobotCommand = z.infer<typeof rawRobotCommandSchema>;

/** Canonical schema for outbound telemetry events emitted by EdgeNode over DataFabric and WebSocket */
export const rawRobotTelemetryEventSchema = z.object(
  {
    timestamp_ns: timestampNsSchema,
    robot_state: RobotStateSchema,
    joint_positions: ArmJointPositionsSchema,
    palm_state: rawPalmStateSchema.default({"is_grasped": false}),
    inference_metrics: rawInferenceMetricsSchema.nullish(),
    command_id: z.string().nullish(),
  },
  { message: 'RobotTelemetryEvent payload must be an object' }
).strict();

export const RobotTelemetryEventSchema = jsonInput.pipe(rawRobotTelemetryEventSchema);
export const robotTelemetryEventSchema = RobotTelemetryEventSchema;

export type RobotTelemetryEvent = z.infer<typeof rawRobotTelemetryEventSchema>;

function unwrapZod<T>(result: {
  success: true;
  data: unknown;
} | {
  success: false;
  error: { issues: Array<{ message: string }> };
}): T {
  if (!result.success) {
    throw new Error(result.error.issues[0]?.message ?? 'Validation failed');
  }
  return result.data as T;
}

export function parsePalmActuatePayload(input: unknown): PalmActuatePayload {
  return unwrapZod<PalmActuatePayload>(palmActuatePayloadSchema.safeParse(input));
}

export function isPalmActuatePayload(input: unknown): input is PalmActuatePayload {
  return palmActuatePayloadSchema.safeParse(input).success;
}

export function parseTrajectoryExecutePayload(input: unknown): TrajectoryExecutePayload {
  return unwrapZod<TrajectoryExecutePayload>(trajectoryExecutePayloadSchema.safeParse(input));
}

export function isTrajectoryExecutePayload(input: unknown): input is TrajectoryExecutePayload {
  return trajectoryExecutePayloadSchema.safeParse(input).success;
}

export function parseEmergencyStopPayload(input: unknown): EmergencyStopPayload {
  return unwrapZod<EmergencyStopPayload>(emergencyStopPayloadSchema.safeParse(input));
}

export function isEmergencyStopPayload(input: unknown): input is EmergencyStopPayload {
  return emergencyStopPayloadSchema.safeParse(input).success;
}

export function parseResetFaultPayload(input: unknown): ResetFaultPayload {
  return unwrapZod<ResetFaultPayload>(resetFaultPayloadSchema.safeParse(input));
}

export function isResetFaultPayload(input: unknown): input is ResetFaultPayload {
  return resetFaultPayloadSchema.safeParse(input).success;
}

export function parseSpawnObjectPayload(input: unknown): SpawnObjectPayload {
  return unwrapZod<SpawnObjectPayload>(spawnObjectPayloadSchema.safeParse(input));
}

export function isSpawnObjectPayload(input: unknown): input is SpawnObjectPayload {
  return spawnObjectPayloadSchema.safeParse(input).success;
}

export function parseClearWorkspacePayload(input: unknown): ClearWorkspacePayload {
  return unwrapZod<ClearWorkspacePayload>(clearWorkspacePayloadSchema.safeParse(input));
}

export function isClearWorkspacePayload(input: unknown): input is ClearWorkspacePayload {
  return clearWorkspacePayloadSchema.safeParse(input).success;
}

export function parsePalmState(input: unknown): PalmState {
  return unwrapZod<PalmState>(palmStateSchema.safeParse(input));
}

export function isPalmState(input: unknown): input is PalmState {
  return palmStateSchema.safeParse(input).success;
}

export function parseInferenceMetrics(input: unknown): InferenceMetrics {
  return unwrapZod<InferenceMetrics>(inferenceMetricsSchema.safeParse(input));
}

export function isInferenceMetrics(input: unknown): input is InferenceMetrics {
  return inferenceMetricsSchema.safeParse(input).success;
}

export function parseErrorFrame(input: unknown): ErrorFrame {
  return unwrapZod<ErrorFrame>(errorFrameSchema.safeParse(input));
}

export function isErrorFrame(input: unknown): input is ErrorFrame {
  return errorFrameSchema.safeParse(input).success;
}

export function parseRobotCommand(input: unknown): RobotCommand {
  return unwrapZod<RobotCommand>(robotCommandSchema.safeParse(input));
}

export function isRobotCommand(input: unknown): input is RobotCommand {
  return robotCommandSchema.safeParse(input).success;
}

export function parseRobotTelemetryEvent(input: unknown): RobotTelemetryEvent {
  return unwrapZod<RobotTelemetryEvent>(robotTelemetryEventSchema.safeParse(input));
}

export function isRobotTelemetryEvent(input: unknown): input is RobotTelemetryEvent {
  return robotTelemetryEventSchema.safeParse(input).success;
}

export const robotIdSchema = z
  .string({
    message: "Invalid robot ID: must be non-empty and not contain slashes or whitespace",
  })
  .min(1, {
    message: "Invalid robot ID: must be non-empty and not contain slashes or whitespace",
  })
  .regex(/^[^/\\\s]+$/, {
    message: "Invalid robot ID: must be non-empty and not contain slashes or whitespace",
  });

export const robotTopicSchema = z
  .string()
  .regex(/^robot\/([^/\\\s]+)\/(command|telemetry)$/)
  .transform((topic) => {
    const parts = topic.split('/');
    return {
      robotId: parts[1],
      channel: parts[2] as 'command' | 'telemetry',
    };
  });

export function robotCommandTopic(robotId: string): string {
  const validId = robotIdSchema.parse(robotId);
  return `robot/${validId}/command`;
}

export function robotTelemetryTopic(robotId: string): string {
  const validId = robotIdSchema.parse(robotId);
  return `robot/${validId}/telemetry`;
}

export function parseRobotTopic(
  topic: string
): { robotId: string; channel: 'command' | 'telemetry' } | null {
  const result = robotTopicSchema.safeParse(topic);
  return result.success ? result.data : null;
}

export function serializeCommand(cmd: RobotCommand): string {
  return JSON.stringify(cmd, (_, v) =>
    typeof v === 'bigint' ? Number(v) : v
  );
}
